/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import pipes.Observer;
import Controller.ControllerView;
import javax.swing.JCheckBox;
import javax.swing.JTextField;
import pipes.ModeloPipes;

/**
 *
 * @author Miqueias
 */
public class View extends javax.swing.JFrame implements Observer{

    ModeloPipes modeloPipes;
    ControllerView controllerView;
    
    
    public View(ModeloPipes modeloPipes) {
        this.modeloPipes = modeloPipes;
        this.controllerView = new ControllerView(modeloPipes,this);
        modeloPipes.attach(this);
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMai = new javax.swing.JCheckBox();
        jInv = new javax.swing.JCheckBox();
        jMin = new javax.swing.JCheckBox();
        jTv = new javax.swing.JCheckBox();
        jTc = new javax.swing.JCheckBox();
        jGerar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jNome = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jResultado = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jOrdem = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Opções"));

        jMai.setText("Maiúsculo");
        jMai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMaiActionPerformed(evt);
            }
        });

        jInv.setText("Inverter");
        jInv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInvActionPerformed(evt);
            }
        });

        jMin.setText("Minúsculo");
        jMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMinActionPerformed(evt);
            }
        });

        jTv.setText("Tirar Vogais");
        jTv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTvActionPerformed(evt);
            }
        });

        jTc.setText("Tirar Consoantes");
        jTc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTcActionPerformed(evt);
            }
        });

        jGerar.setText("Gerar");
        jGerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGerarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jMai)
                        .addGap(18, 18, 18)
                        .addComponent(jInv)
                        .addGap(18, 18, 18)
                        .addComponent(jTc))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jMin)
                        .addGap(18, 18, 18)
                        .addComponent(jTv)))
                .addContainerGap(88, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jGerar)
                .addGap(113, 113, 113))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jMai)
                    .addComponent(jInv)
                    .addComponent(jTc))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jMin)
                    .addComponent(jTv)
                    .addComponent(jGerar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Command Lines"));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jNome, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultado"));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jResultado, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Ordem"));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jOrdem)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jOrdem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMaiActionPerformed
               this.controllerView.trataEvento(evt);      // TODO add your handling code here:
    }//GEN-LAST:event_jMaiActionPerformed

    private void jGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGerarActionPerformed
                this.controllerView.botaoAcionado(evt); // TODO add your handling code here:
    }//GEN-LAST:event_jGerarActionPerformed

    private void jInvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInvActionPerformed
                this.controllerView.trataEvento(evt);     // TODO add your handling code here:
    }//GEN-LAST:event_jInvActionPerformed

    private void jTcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTcActionPerformed
                this.controllerView.trataEvento(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_jTcActionPerformed

    private void jMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMinActionPerformed
                 this.controllerView.trataEvento(evt); // TODO add your handling code here:
    }//GEN-LAST:event_jMinActionPerformed

    private void jTvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTvActionPerformed
                  this.controllerView.trataEvento(evt);   // TODO add your handling code here:
    }//GEN-LAST:event_jTvActionPerformed

    /**
     * @param args the command line arguments
     */
   

    @Override
    public void update() {
        this.jResultado.setText(this.modeloPipes.getNome());
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jGerar;
    private javax.swing.JCheckBox jInv;
    private javax.swing.JCheckBox jMai;
    private javax.swing.JCheckBox jMin;
    private javax.swing.JTextField jNome;
    private javax.swing.JTextField jOrdem;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jResultado;
    private javax.swing.JCheckBox jTc;
    private javax.swing.JCheckBox jTv;
    // End of variables declaration//GEN-END:variables

    
    
    public JTextField getjNome() { 
        return jNome;
    }

    public JTextField getjOrdem() {
        return jOrdem;
    }

    public void setjOrdem(JTextField jOrdem) {
        this.jOrdem = jOrdem;
    }

    public void setjNome(JTextField jNome) {
        this.jNome = jNome;
    }

    public JCheckBox getjInv() {
        return jInv;
    }

    public void setjInv(JCheckBox jInv) {
        this.jInv = jInv;
    }

    public JCheckBox getjMai() {
        return jMai;
    }

    public void setjMai(JCheckBox jMai) {
        this.jMai = jMai;
    }

    public JCheckBox getjMin() {
        return jMin;
    }

    public void setjMin(JCheckBox jMin) {
        this.jMin = jMin;
    }

    public JCheckBox getjTc() {
        return jTc;
    }

    public void setjTc(JCheckBox jTc) {
        this.jTc = jTc;
    }

    public JCheckBox getjTv() {
        return jTv;
    }

    public void setjTv(JCheckBox jTv) {
        this.jTv = jTv;
    }

    
}
